### ISSUE TITLE
Improve initial install experience

### ISSUE THREAD

**Issue by notpeter** [zed-extensions/ruby#37]
Currently the UX for a new user installing the Ruby extension is somewhat sub-par.  If you do not have solargraph or ruby-lsp installed and available in your path, the extension kicks an error:
```
Language server error: ruby-lsp

Unable to find the 'ruby-lsp' command.
-- stderr--
```

Some of this may just be a need for better [zed ruby docs](https://zed.dev/docs/languages/ruby).

For example on macos you would need to do the following:
```
brew install ruby
echo 'export PATH="/opt/homebrew/opt/ruby/bin:$PATH"' >> ~/.zshrc
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"

# ruby-lsp
gem install ruby-lsp
echo 'export PATH="/opt/homebrew/lib/ruby/gems/3.4.0/bin:$PATH"' >> ~/.zshrc
export PATH="/opt/homebrew/lib/ruby/gems/3.4.0/bin:$PATH"

# solargraph
brew install solargraph
```

- Do I need a global install of ruby-lsp? (are there downsides to suggesting `homebrew` ruby)? 
  - I hate suggesting a fixed ruby versionized gem path, but homebrew doesn't suggest adding gem bin to your path.  Perhaps: 
    ```shell
    export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
    export PATH="$(gem environment path | sed 's#:#/bin:#g; s#$#/bin#'):$PATH"
    ``` 
  - What about for Linux users?
- Should we suggest ruby-lsp plugins like (`ruby-lsp-rails`, `ruby-lsp-rspec`)?
  - Do these require any additional config
- Does anyone have a sense of the solargraph / ruby-lsp usage split? (I know ruby-lsp is new-ish)?
  - Solargraph had zero releases in 2024, but development seems to have picked up a bit with 3 releases in 2025.

I'm going to see if I can improve the docs to make sure they work for setting up from a clean mac, but wanted to see if anyone had feedback or other suggestions on how to improve first time user experience.

cc: @vitallium, @ConradIrwin

**Comment by vitallium** [comment]
Hi,

>Do I need a global install of ruby-lsp? (are there downsides to suggesting homebrew ruby)?

It depends. In most cases, the global installation of `ruby-lsp` is enough but if any add-on, for example, `ruby-lsp-rspec`, is required then it's recommended to add `ruby-lsp` to the project's Gemfile. Doing so requires starting the `ruby-lsp` via `bundler`: `bundle exec ruby-lsp`.

>are there downsides to suggesting homebrew ruby

In 99% cases Rubyists rely on a version manager like `rbenv`, `rvm`, `asdf` or `mise` to install the specific Ruby project version defined there. It's important to have the correctly activated Ruby version otherwise LSPs won't work and other stuff too.

>Should we suggest ruby-lsp plugins like (ruby-lsp-rails, ruby-lsp-rspec)?

`ruby-lsp-rails` is installed automatically by `ruby-lsp` if a Rails project is detected. `ruby-lsp-rspec` is an optional gem that must be added to the `Gemfile` but there is also an option to use a composed bundle - https://shopify.github.io/ruby-lsp/composed-bundle.html

>Does anyone have a sense of the solargraph / ruby-lsp usage split? 

No idea, I will ask on social media about that. Even [the latest Ruby survey](https://railsdeveloper.com/survey/2024) does not have such topic.

I was thinking about potential UX improvements and the only way to improve it is to allow a Zed extension to run system commands but that raises many security concerns. Overall, I am happy to help with anything that aims to improve UX of the Ruby extension.

**Comment by ConradIrwin** [comment]
Fixing the docs is a good start, but as mentioned in [#zed-industries/zed/](https://github.com/zed-industries/zed/issues/25099), I would like to get to the point where Zed's ruby integration can install and configures the language server out of the box.

I think you're right that this requires making extensions more powerful, and I also think that's the right trade-off. Given that today they can download arbitrary code from GitHub and run that, it doesn't seem too bad to let them run *some* code off the bat.

What I was imagining is a way for extensions to whitelist in the manifest the things they need to do:
```
allow_exec = [
  "gem install ruby-lsp",
 ]
```

If we were to do something like that, would it actually be enough though? :D

I think it's also important that extensions don't modify people's projects, so we wouldn't want to add things to the Gemfile by default (though we should obviously use the ruby-lsp from the Gemfile if it exists). I also know that there's a significant amount of variation in how gems get installed globally. I was wondering if we could emulate what we do with typescript and set up a fake project in a temporary directory, and run the lsp from there (if they don't already have it in the Gemfile of course); the challenge I guess would be making sure we're using the correct ruby in that directory

**Comment by vitallium** [comment]
>I was wondering if we could emulate what we do with typescript and set up a fake project in a temporary directory, and run the lsp from there (if they don't already have it in the Gemfile of course); the challenge I guess would be making sure we're using the correct ruby in that directory

I am not sure about this idea since I am not familiar with Zed codebase but I was actually thinking about providing `ruby_runtime` in the same as Zed does for Node.js. The idea of this runtime is not to install Ruby but grant access to the system or project Ruby through extension API:

- `ruby-binary-path`: Returns the path to the currently active Ruby binary.
- `gems-latest-version`: Returns the latest version of the given Ruby gem.
- `gems-installed-version`: Returns the installed version of the given Ruby gem, if it exists.
- `gems-install-gem`: Installs the specified Ruby gem.

And so on. That should give flexibility to the Ruby extension and other extensions that rely on Ruby ecosystem. For example, the Ruby DX will be like this:

- Use the `bundle-installed-version` function from the `ruby-runtime` to check if the current project (if any) has any enabled LSP. If yes, start it in the context of the project's gemset.
- Otherwise, use `gems-*` functions from the `ruby-runtime` to install the LSP.


I spent some time today to craft PoC: https://github.com/zed-industries/zed/pull/25350
It does some basic things like installs the Ruby LSP if it's not available but I removed all project-aware settings for now since they work as-is currently. I also didn't implement installing a portable Ruby in case we don't have Ruby at all, but that option is also available.

To test it you need to:

1. Check out the `vs/ruby-runtime` branch and build Zed.
2. Check out the `vs/ruby-runtime` branch of the Ruby extension.
3. Rebuild the Ruby extension to make the Ruby runtime functions available.

I also pushed a version of Ruby extension that uses this runtime to illustrate how it looks in action. Let me know what do you think. Thanks!

**Comment by ConradIrwin** [comment]
Wow, incredible! Thank you :D.

I'll take some time to review this and try to get back to you early next week, but I like this idea a lot.

**Comment by maxdeviant** [comment]
@vitallium The new [`process::Command`](https://docs.rs/zed_extension_api/latest/zed_extension_api/process/struct.Command.html) API is now available in v0.3.0 of the extension API, which is now in Zed Preview v0.178.x.

One change in the released version is that the extension will need to enumerate a list of capabilities indicating which commands it will run and with which arguments/partial argument lists.

There are some more details in https://github.com/zed-industries/zed/pull/26224.

**Comment by vitallium** [comment]
> [@vitallium](https://github.com/vitallium) The new [`process::Command`](https://docs.rs/zed_extension_api/latest/zed_extension_api/process/struct.Command.html) API is now available in v0.3.0 of the extension API, which is now in Zed Preview v0.178.x.
> 
> One change in the released version is that the extension will need to enumerate a list of capabilities indicating which commands it will run and with which arguments/partial argument lists.
> 
> There are some more details in [zed-industries/zed#26224](https://github.com/zed-industries/zed/pull/26224).

Awesome! I've started putting all the required bits into [this pull request](https://github.com/zed-extensions/ruby/pull/48). Just to re-iterate on the vision of the Ruby extension:

## How the logic currently works

The Ruby extension provides support for 3 language servers: `solargraph`, `ruby-lsp` and `rubocop`. By default, `solargraph` is the enabled language server.

The logic is as follows:

1. If the `use_bundler` configuration option is set to true, the Ruby extension attempts to start the language server within the project gems using: `bundle exec <language_server_bin_name> <language_server_args>`
2. Otherwise, the Ruby extension tries to start the language server within the user gemset using: `<language_server_bin_name> <language_server_args>`. This step may fail if the required language server is not installed in the user gems.

## With the newly added [`process::Command`] API

The newly added [`process::Command`] can improve the last step by automatically installing the required language server:

1. If the `use_bundler` configuration option is `true`, the Ruby extension tries to start the LS within the project gems: `bundle exec <language_server_bin_name> <language_server_args>`. This step should likely remain unchanged since, in most cases, a project relies on specific Ruby gem versions that may be incompatible with those in the user gems. Additionally, `rubocop` - a static linter - may also depend on specific Ruby gem versions to apply the correct linting rules.

2. Otherwise, the Ruby extension checks the user gemset for the required language server and attempts to start it. This step is optional and may be best avoided for the reasons outlined below.
3. If the required language server is not found in the user gemset, the Ruby extension will install it while bypassing the user gemset. This approach has two advantages:

   - Preserving the user gems: The Ruby extension does not modify the user's installed gems.
   - Avoiding version conflicts: The user gems may contain incompatible Ruby gem versions.

I have left tasks like checking for new versions and updating the LS gems out of scope for now.

Let me know if that makes sense or if you have any additional thoughts, ideas, or questions. Thanks!

**Comment by ConradIrwin** [comment]
This sounds excellent, thank you! I like that we'll respect the users configuration if they have it, but we can still work even if the havent' configured anything yet.

Upgrades (for the one we manage ourselves) should be pretty straightforward, but seems good to descope so we can get the v1 working.

(Also, I know we need to merge your diagnostics PR too; I'll try and take a look at that this week)

**Comment by vitallium** [comment]
The 1st iteration powered by the Process API has been shipped in v0.7.0 — https://github.com/zed-extensions/ruby/releases/tag/v0.7.0. It's time to collect bugs and feedback. Thank you all!

**Comment by skatkov** [comment]
@vitallium this extension worked for me previously, but after latest update I'm seeing following error:

```
Language server error: ruby-lsp

failed to spawn command. path: "/home/sk/.var/app/dev.zed.Zed/data/zed/extensions/work/ruby/bin/ruby-lsp", working directory: "/home/sk/Code/flex-core", args: []
-- stderr--
```

**Comment by vitallium** [comment]
> [@vitallium](https://github.com/vitallium) this extension worked for me previously, but after latest update I'm seeing following error:
> 
> ```
> Language server error: ruby-lsp
> 
> failed to spawn command. path: "/home/sk/.var/app/dev.zed.Zed/data/zed/extensions/work/ruby/bin/ruby-lsp", working directory: "/home/sk/Code/flex-core", args: []
> -- stderr--
> ```

Hi, sorry about that! We have fixed the issue in https://github.com/zed-extensions/ruby/pull/84, and the fix will be included in v0.7.1. Thanks for your patience!

**Comment by olimart** [comment]
@vitallium  sorry to put that here but still getting

```
Language server error: ruby-lsp

Failed to install gem 'ruby-lsp': Gem command failed (status: 1)
Error: ERROR:  Error installing ruby-lsp:
	There are no versions of sorbet-runtime (>= 0.5.10782) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	sorbet-runtime requires Ruby version >= 2.7.0. The current ruby version is 2.6.10.210.

-- stderr--
```

ruby-lsp is indeed correctly installed but I guess there is some path issue here.
I'm using asdf to manage ruby versions (don't know if related) but I thought this was going to be solved with the recent work on ruby extension.

Anyway, if you know where to look, let me know. Thanks. Great work on the editor.

**Comment by andyw8** [comment]
@olimart you may need to set a default global Ruby version. I have this in `~/.tool-versions`:

```
ruby 3.4.1
```

**Comment by olimart** [comment]
Thanks @andyw8 I already have that in place.

> you may need to set a default global Ruby version. I have this in `~/.tool-versions`:
> 
> ```
> ruby 3.4.1
> ```

**Comment by jwkicklighter** [comment]
I have the same problem, also using `asdf` to manage Ruby. For me, I'm also having an issue with rubocop since I use the `rubocop-rails-omakase` gem in my projects (a default gem with Rails 8). So both `ruby-lsp` and `rubocop` fail.

IMO relying on a default global version, if that had fixed the problem, wouldn't be the correct solution. Based on the experience with other text editors and extensions, I would expect that this extension would use my shell environment so whatever version manager is setup will work correctly.

**Comment by vitallium** [comment]
@jwkicklighter the Ruby extension uses the shell environment of your current project. I suspect that the issue described by @olimart is related to #83 and #82, and should be resolved in v0.7.1, which is currently under review. Thanks!

**Comment by olimart** [comment]
@vitallium not sure what you did but ruby extension v0.7.1 brings together ruby-lsp, standardrb, and tests running. What a treat. Thanks again for your work.

**Comment by jwkicklighter** [comment]
@vitallium 0.7.1 also resolved my issues, thank you!

**Comment by vitallium** [comment]
I think we can close this since we haven't seen many issues with the new activation logic. Thank you all!

**Comment by exalted** [comment]
FWIW; I "had to" `gem install solargraph --install-dir "$HOME/Library/Application Support/Zed/extensions/work/ruby/gems/<⚠️random>" --force` in order to install `solargraph` along side all its transitive dependencies (including `rexml`, `benchmark`, and whatever else is missing)
